services:
  mesin1:
    build: .
    container_name: dino-mesin-1
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60001:8888"
      - "50001:6666"
      - "55555:55555"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin1"
      - "GAME_SERVER=localhost"
      - "SDL_AUDIODRIVER=dummy"
    working_dir: /home/jovyan/work
    volumes:
      - ./work1:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: 172.16.16.101 
    command: >
      sh -c "echo 'Starting server...' &&
             python /home/jovyan/work/server_thread_pool_http.py & 
             /opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"


  mesin2:
    build: .
    container_name: dino-mesin-2
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60002:8888"
      - "50002:6666"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin2"
      - "GAME_SERVER=172.16.16.101"
      - "SDL_AUDIODRIVER=dummy"
    working_dir: /home/jovyan/work
    volumes:
      - ./work2:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: 172.16.16.102
    command: >
      sh -c "/opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"

  mesin3:
    build: .
    container_name: dino-mesin-3
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60003:8888"
      - "50003:6666"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin3"
      - "GAME_SERVER=172.16.16.101"
      - "SDL_AUDIODRIVER=dummy"
    working_dir: /home/jovyan/work
    volumes:
      - ./work3:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: 172.16.16.103
    command: >
      sh -c "/opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"

networks:
  default:
    driver: bridge
  progjar-network:
    name: progjar-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: "progjar-network"  
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24
          gateway: 172.16.16.1